<a href="https://colab.research.google.com/github/VikrantTufani1999/Solvathon_2023/blob/main/Random_Forest_Approach.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('processedDatSet.csv')
dataset = dataset.fillna(0)
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [4]:
dataset.head()
#print(dataset.isnull().any())



Exercise  Depression  Diabetes  Arthritis  Sex  Age_Category  Height_(cm)  \
0         0           0         0          1    0            72          150   
1         0           0         1          0    0            72          165   
2         1           0         1          0    0            62          163   
3         1           0         1          0    1            77          180   
4         0           0         0          0    1            80          191   

   Weight_(kg)    BMI  Smoking_History  Alcohol_Consumption  \
0        32.66  14.54                1                    0   
1        77.11  28.29                0                    0   
2        88.45  33.47                0                    4   
3        93.44  28.73                0                    0   
4        88.45  24.37                1                    0   

   Fruit_Consumption  Green_Vegetables_Consumption  FriedPotato_Consumption  \
0                 30                            16                       12   
1                 30                             0                        4   
2                 12                             3                       16   
3                 30                            30                        8   
4                  8                             4                        0   

   General_Health_Excellent  General_Health_Fair  General_Health_Good  \
0                         0                    0                    0   
1                         0                    0                    0   
2                         0                    0                    0   
3                         0                    0                    0   
4                         0                    0                    1   

   General_Health_Poor  General_Health_Very Good  Heart_Disease  
0                    1                         0              0  
1                    0                         1              1  
2                    0                         1              0  
3                    1                         0              1  
4                    0                         0              0

In [5]:
from sklearn.utils import resample
#create two different dataframe of majority and minority class
dataset_majority = dataset[(dataset['Heart_Disease']==0)]
dataset_minority = dataset[(dataset['Heart_Disease']==1)]
# upsample minority class
df_minority_upsampled = resample(dataset_minority,
                                 replace=True,    # sample with replacement
                                 n_samples= 283883, # to match majority class
                                 random_state=42)  # reproducible results
# Combine majority class with upsampled minority class
dataset_upsampled = pd.concat([df_minority_upsampled, dataset_majority])

In [6]:
X = dataset_upsampled.iloc[:, :-1].values
y = dataset_upsampled.iloc[:, -1].values

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [ ]:
from imblearn.ensemble import BalancedBaggingClassifier
from sklearn.tree import DecisionTreeClassifier
#Create an instance
classifier = BalancedBaggingClassifier(base_estimator=DecisionTreeClassifier(),
                                sampling_strategy='not majority',
                                replacement=False,
                                random_state=42)
classifier.fit(X_train, y_train)
preds = classifier.predict(X_test)

/usr/local/lib/python3.10/dist-packages/imblearn/ensemble/_bagging.py:353: FutureWarning: `base_estimator` was renamed to `estimator` in version 0.10 and will be removed in 0.12.
  warnings.warn(


In [ ]:
#print(preds)
from sklearn.metrics import confusion_matrix, accuracy_score,f1_score
cm = confusion_matrix(y_test, preds)
print(cm)

[[67985  3267]
 [   26 70664]]


In [ ]:
print(accuracy_score(y_test, preds))
print(f1_score(y_test,preds))

0.9768003832551324
0.9772301394679889


In [8]:
from sklearn.ensemble import RandomForestClassifier

In [9]:
classifier_rf = RandomForestClassifier(n_estimators = 30, criterion = 'entropy', random_state = 1)

In [10]:
classifier_rf.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=30, random_state=1)

In [11]:
y_pred = classifier_rf.predict(X_test)

In [12]:
from sklearn.metrics import confusion_matrix, accuracy_score,f1_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(accuracy_score(y_test, y_pred))
print(f1_score(y_test,y_pred))

[[68678  2574]
 [   13 70677]]
0.9817742458187146
0.9820273584315796


In [13]:
pip install pickle-mixin

  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Created wheel for pickle-mixin: filename=pickle_mixin-1.0.2-py3-none-any.whl size=6017 sha256=85a5fa71a698e2c9606a763252caba65af166b5dc5a507240ca1b9f0ebf4c145
  Stored in directory: c:\users\vikrantkumartufani\appdata\local\pip\cache\wheels\d0\9c\0d\8709be17c02b72bf04ea60d8ec64fc46a1554c0fb81e048dd6
Successfully built pickle-mixin
Note: you may need to restart the kernel to use updated packages.


In [14]:
import pickle

In [17]:
with open('C:/Users/VikrantKumarTufani/Downloads/Solvathon_2023-main_vik/Solvathon_2023-main/model_pkl', 'wb') as files:
    pickle.dump(classifier_rf, files)

In [18]:
# load saved model
with open('C:/Users/VikrantKumarTufani/Downloads/Solvathon_2023-main_vik/Solvathon_2023-main/model_pkl' , 'rb') as f:
    lr = pickle.load(f)

In [31]:
# check prediction

lr.predict([[0,0,0,1,0,72,150,32.66,14.54,1,0,30,16,12,0,0,0,1,0]]) # similar

array([0], dtype=int64)

In [20]:
pip install flask_restful

  Obtaining dependency information for flask_restful from https://files.pythonhosted.org/packages/d7/7b/f0b45f0df7d2978e5ae51804bb5939b7897b2ace24306009da0cc34d8d1f/Flask_RESTful-0.3.10-py2.py3-none-any.whl.metadata
     ---------------------------------------- 0.0/52.8 kB ? eta -:--:--
     ------- -------------------------------- 10.2/52.8 kB ? eta -:--:--
     ---------------------- --------------- 30.7/52.8 kB 330.3 kB/s eta 0:00:01
     -------------------------------------- 52.8/52.8 kB 452.3 kB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [21]:
pip install flask_cors

  Obtaining dependency information for flask_cors from https://files.pythonhosted.org/packages/10/69/1e6cfb87117568a9de088c32d6258219e9d1ff7c131abf74249ef2031279/Flask_Cors-4.0.0-py2.py3-none-any.whl.metadata
Note: you may need to restart the kernel to use updated packages.


In [22]:
from flask import Flask, request, redirect
from flask_restful import Resource, Api
from flask_cors import CORS
import os

In [50]:
import pickle
import pandas as pd
import json

def predict_mpg(config):
    ##loading the model from the saved file
    pkl_filename = "C:/Users/VikrantKumarTufani/Downloads/Solvathon_2023-main_vik/Solvathon_2023-main/model_pkl"
    with open(pkl_filename, 'rb') as f_in:
        model = pickle.load(f_in)

    if type(config) == dict:
        df = pd.DataFrame(config)
        print("checkpoint1")
    else:
        df = config
        print("checkpoint2")
        
    #df = pd.DataFrame.from_dict(config, orient='index')

    #data = df.iloc[:1].values
    y_pred = model.predict(df)

    if y_pred == 0:
        return 'Normal'
    elif y_pred == 1:
        return 'Alert Condition'

In [48]:
dct = {
    "Exercise" : 0,
    "Depression" : 0,
    "Diabetes" : 0,
    "Arthritis" : 1,
    "Sex" : 0,
    "Age_Category" : 72,
    "Height_(cm)" : 150,
    "Weight_(kg)" : 34.50,
    "BMI" : 20,
    "Smoking_History" : 1,
    "Alcohol_Consumption" : 0,
    "Fruit_Consumption" : 40,
    "Green_Vegetables_Consumption" : 15,
    "FriedPotato_Consumption" : 14,
    "General_Health_Excellent" : 0,
    "General_Health_Fair" : 0,
    "General_Health_Good" : 0,
    "General_Health_Poor" : 1,
    "General_Health_Very Good" : 0
}

dct = {k:[v] for k,v in dct.items()}
df = pd.DataFrame(dct)
predict_mpg(df)

checkpoint2


C:\Users\VikrantKumarTufani\anaconda3\Lib\site-packages\sklearn\base.py:457: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


'Normal'

In [51]:
app = Flask(__name__)
cors = CORS(app, resources={r"*": {"origins": "*"}})
api = Api(app)

In [52]:
class Test(Resource):
    def get(self):
        return 'Welcome to, Test App API!'

    def post(self):
        try:
            value = request.get_json()
            if(value):
                return {'Post Values': value}, 201

            return {"error":"Invalid format."}

        except Exception as error:
            return {'error': error}

In [53]:
class GetPredictionOutput(Resource):
    def get(self):
        return {"error":"Invalid Method."}

    def post(self):
        try:
            dct = request.get_json()
            print(data)
            print("before predict")
            dct = {k:[v] for k,v in dct.items()}
            df = pd.DataFrame(dct)
            #predict_mpg(df)
            predict = predict_mpg(df)
            print("after predict")
            predictOutput = predict
            return {'predict':predictOutput}

        except Exception as error:
            return {'error': error}

In [54]:
api.add_resource(Test,'/')
api.add_resource(GetPredictionOutput,'/getPredictionOutput')

In [ ]:
if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5000))
    app.run(host='0.0.0.0', port=port)

 * Serving Flask app '__main__'
 * Debug mode: off


 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://18.0.0.181:5000
Press CTRL+C to quit
127.0.0.1 - - [06/Oct/2023 11:45:14] "GET / HTTP/1.1" 200 -


{'Exercise': 0, 'Depression': 0, 'Diabetes': 0, 'Arthritis': 1, 'Sex': 0, 'Age_Category': 72, 'Height_(cm)': 150, 'Weight_(kg)': 34.5, 'BMI': 20, 'Smoking_History': 1, 'Alcohol_Consumption': 0, 'Fruit_Consumption': 40, 'Green_Vegetables_Consumption': 15, 'FriedPotato_Consumption': 14, 'General_Health_Excellent': 0, 'General_Health_Fair': 0, 'General_Health_Good': 0, 'General_Health_Poor': 1, 'General_Health_Very Good': 0}
before predict


C:\Users\VikrantKumarTufani\anaconda3\Lib\site-packages\sklearn\base.py:457: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
127.0.0.1 - - [06/Oct/2023 11:45:29] "POST /getPredictionOutput HTTP/1.1" 200 -


checkpoint2
after predict


C:\Users\VikrantKumarTufani\anaconda3\Lib\site-packages\sklearn\base.py:457: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
127.0.0.1 - - [06/Oct/2023 11:48:25] "POST /getPredictionOutput HTTP/1.1" 200 -


{'Exercise': 0, 'Depression': 0, 'Diabetes': 0, 'Arthritis': 1, 'Sex': 0, 'Age_Category': 72, 'Height_(cm)': 150, 'Weight_(kg)': 34.5, 'BMI': 20, 'Smoking_History': 1, 'Alcohol_Consumption': 0, 'Fruit_Consumption': 40, 'Green_Vegetables_Consumption': 15, 'FriedPotato_Consumption': 14, 'General_Health_Excellent': 0, 'General_Health_Fair': 0, 'General_Health_Good': 0, 'General_Health_Poor': 1, 'General_Health_Very Good': 0}
before predict
checkpoint2
after predict


In [36]:
pip install flask_ngrok

In [45]:
!pip install pyngrok==3.1.0


  Preparing metadata (setup.py) ... done
  Created wheel for pyngrok: filename=pyngrok-3.1.0-py3-none-any.whl size=13550 sha256=2028a1038867c5c3f85c81082ac14c4e3b3a20909498b546e9939e870aa7c167
  Stored in directory: /root/.cache/pip/wheels/f5/fb/4f/be0dd46223d1c142cad946b9829cf3d0e7edd548f000df9cbb
Successfully built pyngrok
  Attempting uninstall: pyngrok
    Found existing installation: pyngrok 4.1.1
    Uninstalling pyngrok-4.1.1:
      Successfully uninstalled pyngrok-4.1.1


In [48]:
!pip install flask_ngrok

In [50]:
from flask_ngrok import run_with_ngrok
app = Flask(__name__)
run_with_ngrok(app)

In [49]:
!ngrok authtoken ""

Authtoken saved to configuration file: /root/.ngrok2/ngrok.yml


In [51]:
app.run()

 * Serving Flask app '__main__'
 * Debug mode: off


INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
INFO:werkzeug:Press CTRL+C to quit


 * Running on http://1a1b-34-118-250-29.ngrok.io
 * Traffic stats available on http://127.0.0.1:4040


INFO:werkzeug:127.0.0.1 - - [06/Oct/2023 07:45:09] "GET / HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2023 07:45:10] "GET /favicon.ico HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2023 07:45:37] "GET / HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2023 07:45:38] "GET /favicon.ico HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2023 07:45:38] "GET / HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2023 07:45:44] "GET / HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2023 07:45:45] "GET /favicon.ico HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2023 07:45:46] "GET / HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2023 07:45:47] "GET /favicon.ico HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2023 07:45:47] "GET / HTTP/1.1" 404 -
